### ISSUE TITLE
Veritabanı teknolojisi

### ISSUE THREAD

**Issue by erkanceylan** [adervis3/Adamlik-Testi#2]
Beyler sa :) veritabanı teknolojisi için postgresql yerine mysql kullansak sorun olur mu ? Öyle daha kolay olcak gibime geldi de.

**Comment by burrakk** [comment]
as kanka mysql daha mantıklı olur bence de . Daha sık kullanılıyor piyasada , stackoverflow da filan bi sıkıntı çıktığında daha rahat çözüm buluruz.
